### ISSUE TITLE
Add an option to optimize both text sizes

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#100]
Currently, the longest line dictates the optimum text size:

![success](http://memegen.link/success/short/a-very-long-sentence-that-will-wrap-and-cause-the-font-size-to-shrink.jpg)

Add an option (perhaps `?optimize=separate` where the default is `?optimize=together`) to optimize the font size on the top and bottom separately.

**Comment by CptSpaceToaster** [comment]
I think the default option should imply `separate`

**Comment by vanossj** [comment]
added support for this in image.py on seperate-font-sizes branch. I'll let someone else handle the web portion

![seperate_fonts_sizes](https://cloud.githubusercontent.com/assets/8310169/9532179/fd9ae72e-4cd7-11e5-863f-5aeaf658feb0.png)

**Comment by jacebrowning** [comment]
Here's branch: https://github.com/jacebrowning/memegen/pull/101

**Comment by jacebrowning** [comment]
Based on the new renderings of the images above, this is no longer an issue.
