### ISSUE TITLE
Unicode characters are not supported.

### ISSUE THREAD

**Issue by tgoyer** [jacebrowning/memegen#103]
Some unicode not supported.  Probably a font character set issue.

Example:  H₂O

**Comment by jacebrowning** [comment]
Confirmed. The subscript `2` is rendered as a box: http://memegen.link/iw/h%E2%82%82o.jpg

**Comment by jacebrowning** [comment]
Maybe someone can find a good open-source font to put here: https://github.com/jacebrowning/memegen/tree/master/data/fonts

**Comment by Miterion** [comment]
This website states that subscript two is a supported character by the impact font. 
http://www.fileformat.info/info/unicode/font/impact/list.htm

**Comment by cpchen** [comment]
how about using the current font as a fallback font when you can't render it in Impact, and using Impact as the default?

**Comment by jacebrowning** [comment]
Is there a way to detect "failed rendering"?
