### ISSUE TITLE
Missing page title

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/memegen#107]
Right now it just says "memegen.link" on the tab.

**Comment by jacebrowning** [comment]
What **should** it say?

**Comment by joshfriend** [comment]
"ALL YOUR MEMES ARE BELONG TO US!"

**Comment by CptSpaceToaster** [comment]
Can it select from a list of random phrases?

**Comment by jacebrowning** [comment]
I'm going to leave it as "memegen.link" while that remains the domain.
