### ISSUE TITLE
Templates 404-ing despite appearing in list

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#111]
For some reason, these don't show up:

* http://memegen.link/templates/awkward-awesome
* http://memegen.link/templates/awesome-awkward

despite appearing in:

http://memegen.link/templates/

**Comment by jacebrowning** [comment]
@ThomasWo I just noticed that these aren't working after merging. I'm not sure what's going on.

**Comment by ThomasWo** [comment]
They are the first templates with hyphens in the name, maybe that could be something?

**Comment by ThomasWo** [comment]
Is there a reason that https://github.com/jacebrowning/memegen/blob/master/memegen/domain/template.py#L68 strips hyphens from template keys?  That's where it's going wrong, the hyphen is stripped and awesome-awkward becomes awesomeawkward.

I could push a patch for this, but I don't know why '-' was included on that list in the first place.

**Comment by jacebrowning** [comment]
The hyphens were stripped because when guessing a template alias, one might now know if it is `good-guy-greg`, `goodguy-greg` or `goodguygreg`. Perhaps both stripped and non-stripped forms should be allowed.
