### ISSUE TITLE
Keep this name?

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#119]
I'm considering paying to host this app on Heroku as I use it regularly and it gets thousands of page views a day.

What does everyone think about http://memegen.link?

It's simply and the purpose is fairly obvious, but there are many other sites branded "meme gen(erator)". Are there any other available URLs that could work better?

**Comment by jacebrowning** [comment]
http://instantme.me was one of the original ideas.

**Comment by jacebrowning** [comment]
One option could be to keep http://memegen.link as the API and use http://instantme.me as a static website with a meme generation form...

**Comment by CptSpaceToaster** [comment]
I think I prefer memegen.link now that I've been using it... anything different will just invoke my resistance to change.

I'm fine either way.  Were you heavily debating switching to instantme.me at some point, and now you're having second thoughts?  Or is something pushing you away from memegen.link?

**Comment by jacebrowning** [comment]
It was one of the original ideas: https://docs.google.com/document/d/1CqNlQkAjlW3vvnmNgYGzVccksc4ADoNh3f7VAW8Nh_U/edit?usp=sharing

The main benefit to changing it would be to get it listed here: https://www.reddit.com/r/memes
There is already a "MemGen".

**Comment by jacebrowning** [comment]
Thanks for the feedback! It will stay as http://memegen.link.

**Comment by CptSpaceToaster** [comment]
Hmmm... I never thought to check github before: https://github.com/cmdrkeene/memegen

**Comment by jacebrowning** [comment]
![sohot](http://memegen.link/sohot/meme-generation/is-so-hot-right-now.jpg)
