### ISSUE TITLE
Possible improvements to /latest

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/memegen#153]
WIP architecture:

* Whenever a meme is generated, store it's url or some identifying information in Redis as the latest one.
* When someone requests `/latest.jpg`, look up the last generated one in Redis and return a `307 TEMPORARY REDIRECT` redirect to it.

This would have the following advantages to the current setup:

* Fixes any strange concurrency issues that might happen with multiple dynos working with separate file systems causing `latest.jpg` to be different depending on which one handles your request. 
* `/latest` HTML page would be able to use the actual URL of what the latest meme was.
* Since the `/latest.jpg` would no longer return an image, it would be much less expensive to call and the client's can intelligently cache the images that it redirects to.

**Comment by jacebrowning** [comment]
If I'm understanding this correct, you're not really proposing changes to `/latest`, but to `/latest.jpg`?

**Comment by joshfriend** [comment]
Both actually. Since you know the URL of the latest meme, you can render the latest page html using the actual URL of the image (and include a link to it too).

**Comment by jacebrowning** [comment]
Sounds good!

I have not used Redis before. It is going to be as simple as capturing the results of the [image route](https://github.com/jacebrowning/memegen/blob/2340fef2be0cd0f8cfc274ce189ba7d9cd0fbde3/memegen/routes/image.py#L42) and deleting some [store code](https://github.com/jacebrowning/memegen/blob/2340fef2be0cd0f8cfc274ce189ba7d9cd0fbde3/memegen/stores/image.py#L23-L27)?

Can Redis run in the same process? I see lots of talk of a "Redis server".

**Comment by joshfriend** [comment]
The `create_image` call would probably be the best place to set the latest meme since that method is called by several endpoints. Then the `latest()` method of image store would just return the value found in Redis and `create()` would no longer need the symlinking code.

Redis a separate server, but Heroku has a [free one](https://elements.heroku.com/addons/heroku-redis) that works well.

**Comment by jacebrowning** [comment]
I like the idea of doing this in the store. This should easily support `get_latest(10)`, `get_most_popular()`, etc.

What are the advantages of running a separate Redis server vs. simply storing the results of `create()` in a dictionary on the store instance?

**Comment by joshfriend** [comment]
Since you run multiple Gunicorn processes, each of them would have their own separate tracking dict of the latest image generated by that process. Thus, latest wouldn't actually be the latest meme, it would just be the latest one generated by whatever process services your request.

**Comment by jacebrowning** [comment]
I'm on board. Are you willing to start an implementation for this? I'll install the add-on.

**Comment by jacebrowning** [comment]
`REDIS_URL` is set.

**Comment by joshfriend** [comment]
I'm not sure how much I'll be able to access internet this weekend, but I'll play with it after...

**Comment by jacebrowning** [comment]
Considering that `/latest` is simply for fun and not a critical portion of the API, I'm going to close this and the stale PR. Feel free to create a new PR in the future!
