### ISSUE TITLE
/latest refreshes and loses meme if it lost the internet

### ISSUE THREAD

**Issue by theovoss** [jacebrowning/memegen#155]
If you are on /latest and turn off your internet connection, the meme disappears.

**Comment by jacebrowning** [comment]
What would you like to have happen? Does the image reappear when the connection is resumed? This site is not intended to work offline.

**Comment by theovoss** [comment]
I guess only replace the image if it received a new one. Though since it is a website, I guess offline doesn't really matter.

**Comment by jacebrowning** [comment]
I don't think this is actionable.
