### ISSUE TITLE
Make Facebook posting work correctly

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#166]
This is no good:

<img width="518" alt="screen shot 2016-03-17 at 8 41 09 pm" src="https://cloud.githubusercontent.com/assets/939501/13865333/c0c4f116-ec80-11e5-999f-f6ea5e371f03.png">

**Comment by mattdiamond** [comment]
Isn't this just a consequence of the generated image not being exactly square, and therefore being auto-cropped? Not sure what the appropriate fix would be...

**Comment by jacebrowning** [comment]
It could be. I'm not sure where the black border is coming from through. Why would it crop the sides of the image only to add a black border to the sides?

**Comment by mattdiamond** [comment]
Not sure. Also strange: if you refresh once or twice, the black bars go away and the image is no longer cropped. Perhaps it's some kind of intermediate state while the image is processing? Maybe this isn't really an issue.

**Comment by jacebrowning** [comment]
After additional testing, it seems you may be right. I registered the app with Facebook just in case.
