### ISSUE TITLE
POST /templates/

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#199]
This is referring to:

```
$ http POST http://memegen.link/templates/
HTTP/1.1 403 FORBIDDEN
Connection: keep-alive
Content-Length: 92
Content-Type: application/json
Date: Fri, 27 May 2016 11:19:39 GMT
Server: gunicorn/19.3.0
Via: 1.1 vegur

{
    "message": "https://raw.githubusercontent.com/jacebrowning/memegen/master/CONTRIBUTING.md"
}
```

**Comment by GusCaplan** [comment]
uhhh... this works...

**Comment by jacebrowning** [comment]
I updated the description to clarify. While the API supports POSTing to create new **images**, the only way to create new templates right now is through GitHub.

However, I should just close this issue because I like the current behavior. Thanks for bringing it up!
