### ISSUE TITLE
How do you run this application?

### ISSUE THREAD

**Issue by metalaureate** [jacebrowning/memegen#212]
A stupid question... but how do you run the server? :)

I have gotten as far as creating a docker container based on python 3.5, and running

`python setup.py install`

This generates

Installed /usr/local/lib/python3.5/site-packages/MarkupSafe-0.23-py3.5-linux-x86_64.egg
Finished processing dependencies for MemeGen==2.1

What next? I know little of python, sorry. I am trying to deploy memgen as a docker container.

**Comment by jacebrowning** [comment]
Current, this application targets Heroku using Gunicorn. Assuming you're looking to run the app in "production mode", I'd recommend looking at how the `Procfile` invokes the app:

```sh
gunicorn manage:app --config gunicorn.config.py
```

**Comment by metalaureate** [comment]
That worked! Thanks!

Dockerfile

```
FROM python:latest
ADD ./ /usr/local/src/meme-gen/
RUN apt-get -y update && apt-get -y install imagemagick
WORKDIR /usr/local/src/meme-gen/
RUN  python setup.py install
CMD gunicorn manage:app --config gunicorn.config.py
```

**Comment by metalaureate** [comment]
@jacebrowning Above and beyond the call of duty, but would you know how to tell gunicorn to bind to 0.0.0.0, not 127.0.0.1? I need to do that to expose port 8000 on docker.

**Comment by metalaureate** [comment]
Ok I figured that out - sorry for being lazy.

`gunicorn manage:app -b 0.0.0.0:8000 --config gunicorn.config.py`

**Comment by jacebrowning** [comment]
Does this option do it? http://docs.gunicorn.org/en/stable/settings.html#bind
