### ISSUE TITLE
Create a testbed for `/magic` route patterns

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#215]
The http://memegen.link/magic API uses regular expressions to "guess" what meme you're trying to match. I'd like to create a better way to test these patterns.

**Comment by GusCaplan** [comment]
npmjs.org/package/fuzzy

**Comment by jacebrowning** [comment]
I'm quite sure where or how a JavaScript/Node library would fit in here, but I'll look into it.
