### ISSUE TITLE
A way to pass in the desired font in the URL?

### ISSUE THREAD

**Issue by calophi** [jacebrowning/memegen#216]
A number of us dislike this new "blockier" font and feel that memes should only be in Impact. We'd like a way to force the font to be Impact (or any other font you have uploaded to the project, I suppose).

**Comment by jacebrowning** [comment]
Just as a point of reference, the new font was chosen to support unicode (https://github.com/jacebrowning/memegen/issues/103). If you know of a version of Impact that supports unicode, I'd be happy to use that as the default font.

Having said that, I like the idea of being able to select fonts from the URL.

Would something like `?font=impact` work?

**Comment by calophi** [comment]
Hi  Sorry for the delay. Yes, that's basically all we want. I don't know of a way to use impact with unicode either, but the people on my slack team are being whiny about the font and I want them to shut up, haha. If you have time, I'd appreciate it.

**Comment by jacebrowning** [comment]
@calophi How's this looking so far? These URLs will remain active until the PR merges:

- https://memegen-link-pr-218.herokuapp.com/api/fonts
- http://memegen-link-pr-218.herokuapp.com/joker/pick-a-better-font/people-lose-their-minds.jpg?font=impact

**Comment by jacebrowning** [comment]
Note that due to caching, the font cannot (immediately) be changed once the image has been generated.

**Comment by jacebrowning** [comment]
I'm going to merge the associated PR. If you have any more feedback, please create a new issue.
