### ISSUE TITLE
Add SSL to memegen.link

### ISSUE THREAD

**Issue by GusCaplan** [jacebrowning/memegen#222]
i feel like [the hosted version](http://memegen.link) should have tls/ssl. just throwing that out there.

**Comment by jacebrowning** [comment]
What is the cheapest way to do this on Heroku? I don't make any money on this service, so I'm not quite ready to incur that cost.

**Comment by joshfriend** [comment]
Heroku offers [free ssl endpoints (SNI only)](https://devcenter.heroku.com/articles/ssl-beta), but you still have to provide the certificate. 

LetsEncrypt is a free option for getting a certificate, but was a total nightmare to set up validation for the last time I used it on a Heroku app. This was without support in certbot for DNS validation though, so it  _should_ be easier to validate domains associated with a PaaS hosted app once that is complete.

The other issue with LetsEncrypt certs is the 90 day expiration time. There would have to be an automated process to renew the certificate in place to keep things up to date.

Thats a lot of setup work and upkeep for something that doesn't really add any value to the service IMO

**Comment by jacebrowning** [comment]
Clients can also point to https://memegen-link.herokuapp.com/ if they require SSL.

**Comment by GusCaplan** [comment]
@jacebrowning cloudflare (i use them) offers a free plan with free ssl using their proxy, which might also make things better in the long run, considering their proxy also has caching and such.

**Comment by jacebrowning** [comment]
I will look into that. Thanks!

**Comment by jacebrowning** [comment]
How does this look? https://memegen.link

**Comment by joshfriend** [comment]
LGTM :+1:

![](https://i.imgur.com/IRNbnjA.png)

**Comment by jacebrowning** [comment]
I need to disable caching on https://memegen.link/latest.jpg before forcing SSL.

**Comment by jacebrowning** [comment]
CloudFlare should now be forcing SSL. Please confirm.

**Comment by joshfriend** [comment]
Confirmed:

```
$ http memegen.link
HTTP/1.1 301 Moved Permanently
CF-RAY: 2dc11f7316ab5564-ORD
Connection: keep-alive
Date: Fri, 02 Sep 2016 12:56:35 GMT
Location: https://memegen.link/
Server: cloudflare-nginx
Transfer-Encoding: chunked
```

There are no HSTS headers though.

**Comment by jacebrowning** [comment]
Updated. How's that look?

**Comment by joshfriend** [comment]
I think `max-age=0` is wrong. It appears to tell the browser to [stop enforcing HSTS for the domain.](https://tools.ietf.org/html/rfc6797#section-6.1.1) `max-age=31536000` (1 year) is what you want I think.

**Comment by jacebrowning** [comment]
Looks like CloudFlare's recommended (and longest) options is 6 months.

**Comment by joshfriend** [comment]
That should be fine :+1:
