### ISSUE TITLE
Redirection logic doesn't keep query params!

### ISSUE THREAD

**Issue by cpchen** [jacebrowning/memegen#223]
See

http://memegen.link/philosoraptor/why-do-rhetorical-questions/use-question-marks.jpg?font=impact

vs

http://memegen.link/philosoraptor/why-do-rhetorical-questions/use-question-marks%3F.jpg?font=impact

The second link redirects and changes the %3F into a ~q, but loses the font query param :(

**Comment by jacebrowning** [comment]
Thanks for the bug report!

This fix should be deployed in a few minutes. Please reopen this issue if you're still seeing the bug.

**Comment by cpchen** [comment]
Confirmed the fix.
