### ISSUE TITLE
Image caching doesn't include font as a key

### ISSUE THREAD

**Issue by cpchen** [jacebrowning/memegen#224]
See

http://memegen.link/philosoraptor/why-do-rhetorical-questions/use-question-marks.jpg?font=impact

and then go to

http://memegen.link/philosoraptor/why-do-rhetorical-questions/use-question-marks.jpg

The second one still keeps it at Impact even though I didn't want it to. My guess is that the image cache doesn't include the font as a key.

**Comment by cpchen** [comment]
Similar to #188?

**Comment by jacebrowning** [comment]
Yeah, this is actually the same bug as #188, so I'm going to close this one.
