### ISSUE TITLE
Has someone migrated this to C#? 

### ISSUE THREAD

**Issue by fercom** [jacebrowning/memegen#234]
I want to use this API on my own API but I only know C#, can somebody help me to migrate it? Thanks

**Comment by jacebrowning** [comment]
You can find some code examples on GitHub with this search:

https://github.com/search?l=csharp&q=memegen.link&type=Code&utf8=%E2%9C%93

Perhaps a maintainer on one of these repositories could help you.

**Comment by fercom** [comment]
ok, thank you
