### ISSUE TITLE
Application Error in attempting to use custom template

### ISSUE THREAD

**Issue by ThomasWo** [jacebrowning/memegen#235]
The link below causes memegen.link to spin for a long time until returning an Application Error (reliably reproducible with multiple attempts on my machine with Chrome, uBlock Origin was disabled).

Link: https://memegen.link/api/custom/take-everything-out-of-abp/and-put-it-into-ublock-origin.jpg?alt=https://i1.kym-cdn.com/entries/icons/original/000/012/988/madkarma.PNG

A test of a different templet works: https://memegen.link/api/custom/test.jpg?alt=https://www.google.com/logos/doodles/2016/yma-sumacs-94th-birthday-5639073181990912.2-hp.jpg

**Comment by ThomasWo** [comment]
<img width="1761" alt="screen shot 2016-09-13 at 6 34 49 pm" src="https://cloud.githubusercontent.com/assets/1694386/18493948/5af8cdfa-79e1-11e6-8fc9-6cbb5b285d89.png">

**Comment by jacebrowning** [comment]
https://i1.kym-cdn.com/entries/icons/original/000/012/988/madkarma.PNG by itself fails to load for me over HTTPS.

**Comment by jacebrowning** [comment]
It's possible the API is forcing all external links to use SSL to avoid mixed content...

**Comment by jacebrowning** [comment]
Some more testing here would be appreciated.

**Comment by ThomasWo** [comment]
Sorry, I should have included this in the original bug report.  I had attempted to use both http and https in my test cases and both failed to generate an image.

Interestingly, using https://memegen.link/api/take-everything-out-of-abp/and-put-it-into-ublock-origin.jpg?alt=http://i1.kym-cdn.com/entries/icons/original/000/012/988/madkarma.PNG I only received a blank screen as output for the first few tries, then it started working again...

So I guess I'll close this as Huisenbug and reopen if it reappears?

**Comment by jacebrowning** [comment]
This first failed attempt might have cached a blank image...

Please reopen this if you can find a way to reproduce it.

**Comment by jacebrowning** [comment]
I am definitely seeing weirdness around custom images, but I can't quite pinpoint it.
