### ISSUE TITLE
ongoing issues that might not be fixed part 42: transparency

### ISSUE THREAD

**Issue by GusCaplan** [jacebrowning/memegen#238]
Hai there

I'm sure you guys know about this, but images with transparency go from
![](https://cdn.discordapp.com/emojis/209815959546888192.png "so far so good...")
to
![](https://cdn.discordapp.com/attachments/113743192305827841/226404863808897024/226404858570342404.png "ouch")
if i get time i might look into this myself, but until then, i thought i would just bring it up in case anyone has more free time than me

**Comment by jacebrowning** [comment]
It doesn't seem that [JPEG can support transparency](http://stackoverflow.com/a/16906178/429533), but it would be nice if Pillow consistently converted the transparent later to `#FFFFFF`.

**Comment by jacebrowning** [comment]
@GusCaplan can you provide the https://memegen.link URLs that produced the above images to use as test cases?

**Comment by GusCaplan** [comment]
@jacebrowning i don't have them, my friend made them, but i was thinking of adding pngs into this if i have time 😉

**Comment by jacebrowning** [comment]
This should be working now thanks to #239: https://memegen.link/custom/meme2/_.jpg?alt=https://cdn.discordapp.com/emojis/209815959546888192.png
