### ISSUE TITLE
Add "essential" meme templates 

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#24]
- [x] mordor: One Does Not Simply
- [x] everywhere: X, X Everywhere
- [x] fwp
- [x] success: Success Kid
- [x] wonka
- [x] officespace: That Would Be Great
- [x] doge
- [x] damnhigh: Too Damn High
- [x] whatif: Matrix Morpheus
- [x] ggg
- [x] interesting: I don't always...
- [x] keanu
- [x] live: Do It Live
- [x] icanhaz: I Can Haz Cheezburger

**Comment by CptSpaceToaster** [comment]
doge is in as per https://github.com/jacebrowning/memegen/pull/29

**Comment by jkloo** [comment]
http://memegen.link/buzz/checklists/checklistsEverywhere.jpg

**Comment by jacebrowning** [comment]
That reminds me, I want a feature that will generate Markdown image links to do:

![X, X Everywhere](http://memegen.link/buzz/checklists/checklistsEverywhere.jpg)

**Comment by CptSpaceToaster** [comment]
[ ] [philosoraptor](http://knowyourmeme.com/memes/philosoraptor)
[ ] [[10] guy](http://knowyourmeme.com/memes/10-guy)
