### ISSUE TITLE
Add ability to use UTF symbols. 

### ISSUE THREAD

**Issue by sergio-fry** [jacebrowning/memegen#281]
Can't write memes in Russian, which is very wanted.

**Comment by jacebrowning** [comment]
Can you post a link with your test case? It's possible we just need to add another font.

**Comment by sergio-fry** [comment]
Top text: "А теперь представь"
Bottom text: "что в ruby есть типизирование"

result link: https://memegen.link/buzz/%D0%B0-%D1%82%D0%B5%D0%BF%D0%B5%D1%80%D1%8C-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%8C/%D1%87%D1%82%D0%BE-%D0%B2-ruby-%D0%B5%D1%81%D1%82%D1%8C-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.jpg

![](https://memegen.link/buzz/%D0%B0-%D1%82%D0%B5%D0%BF%D0%B5%D1%80%D1%8C-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%8C/%D1%87%D1%82%D0%BE-%D0%B2-ruby-%D0%B5%D1%81%D1%82%D1%8C-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.jpg)

**Comment by sergio-fry** [comment]
It is Russian BTW.

**Comment by jacebrowning** [comment]
MemeGen accepts a font as a query parameter. Impact supports these characters:

https://memegen.link/buzz/%D0%B0-%D1%82%D0%B5%D0%BF%D0%B5%D1%80%D1%8C-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%8C/%D1%87%D1%82%D0%BE-%D0%B2-ruby-%D0%B5%D1%81%D1%82%D1%8C-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.jpg?font=impact

![](https://memegen.link/buzz/%D0%B0-%D1%82%D0%B5%D0%BF%D0%B5%D1%80%D1%8C-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%8C/%D1%87%D1%82%D0%BE-%D0%B2-ruby-%D0%B5%D1%81%D1%82%D1%8C-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.jpg?font=impact)

You can play around with these fonts here: https://memegen.link/custom

**Comment by sergio-fry** [comment]
Nice! But there is no font selector at https://memegen.link/ site.

**Comment by jacebrowning** [comment]
OK. I made an issue for that https://github.com/jacebrowning/memegen/issues/282.
