### ISSUE TITLE
API not accessible from other browser applications

### ISSUE THREAD

**Issue by jasich** [jacebrowning/memegen#285]
Making calls to `https://memegen.link/api` from a JavaScript browser based application yields the following error in the developer console:

```
XMLHttpRequest cannot load https://memegen.link/api/templates/. No 
'Access-Control-Allow-Origin' header is present on the requested resource. Origin
'http://localhost:3449' is therefore not allowed access.
```

Since the API only allows GET, I suggest setting the following in the Flask API to allow for GET requests from any domain.

```
Access-Control-Allow-Origin: '*'
Access-Control-Allow-Methods: 'GET, OPTIONS',
Access-Control-Allow-Headers: ${echo headers received from client}
```

This does weaken the security by allowing all origins, but since it's a GET only API I would think this shouldn't cause issues.

**Comment by jacebrowning** [comment]
What does `Access-Control-Allow-Header` do? What would happen if it were set to `*`?

**Comment by jasich** [comment]
It limits the HTTP headers that the client send to the server.  It [looks](http://stackoverflow.com/questions/13146892/cors-access-control-allow-headers-wildcard-being-ignored) like the `*` value was recently added, but browser support may be available for it.  Typically I've seen people just loop through the received request header names and set those as the values.  That way you don't have to explicitly allow headers which you may not know ahead of time.

**Comment by jacebrowning** [comment]
Is this usable from another JavaScript application?

https://memegen-link-pr-286.herokuapp.com/api/templates/

**Comment by jasich** [comment]
Yep, that seems to work.
