### ISSUE TITLE
Enable Rich Sharing of Content

### ISSUE THREAD

**Issue by jasich** [jacebrowning/memegen#311]
Twitter & Facebook can show a preview when you post a link to their site if you use specific HTML `meta` tags in your returned HTML document. [Twitter example](https://dev.twitter.com/cards/markup)

This would be cool for memegen (and clients :wink:) because users would not have to download/upload images to share them on Social Media, but instead can just share links and they would show up on these sites.

**Comment by jacebrowning** [comment]
We tried to get this working a while back. I'd love to see this happen!

**Comment by jasich** [comment]
I got this working for one of my own sites a few years ago.  It seemed simple so I'll try to put together a PR for it.

**Comment by jasich** [comment]
The end goal of this is to be able to share a link on a social network and have a rich media rendering of it for end users.  Major social networks support specific HTML `meta` tags to support this.  So far I've just been working on Twitter to support this, but the other networks would be implemented in a similar manner.

Twitter works by scanning tweets for links and then having it's TwitterBot make a request for the content of the link. If the `Content-Type` header of the HTTP response is `text/html` then Twitter will then look for Twitter specific `meta` tags and use those to render a [Twitter Card](https://dev.twitter.com/cards/getting-started).  One of the supported `meta` tags is `twitter:image`, which is used to display an image within a Tweet.  We'll want to use this since the primary function of Memegen is rendering images.

When Memegen receives a meme URL it checks the `Accept` HTTP header from the client to see if the request is for `text/html`.  Unfortunately it looks like both Twitter & Slack send a request with `*/*` as the value for the `Accept` header, which means Memegen always responds with an image (which is good default behavior).  Because Memegen uses the same URL for both the HTML & image content, Memegen can't currently support Twitter Cards for sharing.

Discussing this with @jacebrowning a possible solution is to use query params to modify the response of Memegen specifically for this use case.  For example you could use the following query params in combination with meme URL:

- `?share=true` - Returns HTML with the proper HTML meta tags for social sharing
- `?share-format={twitter|facebook|other}` - Returns an Image that has it's size and aspect ratio optimized for a specific social sharing platform.  The format would be optimized to prevent cropping of text when rendered on the social network.

Twitter Example:
A client would then have a specific Twitter sharing button that would add the the `?share=true` query param to a share URL.  (e.g. https://twitter.com/home?status=http%3A//b0bddfb7.ngrok.io/aag/boo/aliens-man.jpg?share=true).  Any requests for that link would get an HTML response from the Memegen API with `twitter:image` `meta` tag that would reference the image using a URL with the `?share-format=twitter` query param added to it.

**Comment by jacebrowning** [comment]
That all sounds good to me. Thanks for doing the research!

Maybe we combine to two params into into one? `(?share=twitter)`

How would a user go about creating a share link?

**Comment by jasich** [comment]
For the `share` query param you don't need to know what network it will be.  We'll just add all the meta tags for all networks supported.  You only need to know when referencing the image that will be shown.

I found this online [share link generator](http://sharelinkgenerator.com/) that I'm using to determine how to generate a link right now.  We could back that data into the meme info returned to clients too, but I think it's better to let clients generate that.
