### ISSUE TITLE
Add a share button to the UI

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#315]
I will also document `?share=true` in the CHANGELOG once I'm sure it's working correctly for clients.

**Comment by jacebrowning** [comment]
The client should request `280x150`.

**Comment by jacebrowning** [comment]
Also document size params.

**Comment by jacebrowning** [comment]
@jasich It seems that Twitter still crops the images a bit: https://twitter.com/memegen_link/status/817942638930329601

So I'm not sure about the proper dimensions.

**Comment by jacebrowning** [comment]
I wonder if we should request 2-3x the image size and let Twitter scale it.

**Comment by jasich** [comment]
So request something larger so that it will have some fill around it and that way Twitter just crops the fill?

**Comment by jacebrowning** [comment]
Yeah, maybe.

http://sproutsocial.com/insights/social-media-image-sizes-guide/ suggests `width=506&height=253`.

**Comment by jasich** [comment]
440x220 looks pretty good: https://twitter.com/memegen_link/status/818468184537833473

**Comment by jacebrowning** [comment]
Doubling the resolution looks even better: https://twitter.com/memegen_link/status/818475817168764929

**Comment by jasich** [comment]
nice!

**Comment by jacebrowning** [comment]
The only open issue is that we'd like the link to take you to the full image, not the padded version.

**Comment by jasich** [comment]
We could do some UserAgent sniffing for this.  Their requests should come from `TwitterBot` I think.  Similar thing for Facebook.

**Comment by jacebrowning** [comment]
`og:url` only used by Facebook? https://github.com/jacebrowning/memegen/blob/4916e4c95b2ddd0bb6efb7089bb2d246afeb4498/memegen/templates/image.html#L9

**Comment by jasich** [comment]
Twitter can use og:url, og:title, og:description, & og:image, but they check for their own specific ones first supposedly [source](https://dev.twitter.com/cards/getting-started#twitter-cards-and-open-graph).  We can use these facts to our advantage.

**Comment by jacebrowning** [comment]
I added the Twitter image dimensions into the template (https://github.com/jacebrowning/memegen/commit/1609074226d9484e9118464711409c5f641d58f3). Sharing an image with `?share=true` should work automatically now.

**Comment by jacebrowning** [comment]
https://twitter.com/memegen_link/status/818577902555963394
