### ISSUE TITLE
'share' query param cannot be used with 'alt' 

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#321]

**Comment by jasich** [comment]
why's that?

**Comment by jacebrowning** [comment]
The dimension parameters are appended naively, yielding a URL with two `?`s in it: https://memegen.link/custom/helping-build-meme-clients/you-da-real-mvp.jpg?alt=https://imgflip.com/s/meme/You-The-Real-MVP-2.jpg&share=true
