### ISSUE TITLE
Share links don't render the same as comments

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#327]
This is not respecting:

```
<meta property="og:image" content="https://memegen.link/mw/you're-gonna-meet-some-trolls/i-guarantee-it.jpg?height=492&width=940" />
<meta property="og:image:width" content="940" />
<meta property="og:image:height" content="492" />
```

<img width="548" alt="screen shot 2017-01-17 at 12 32 34 am" src="https://cloud.githubusercontent.com/assets/939501/22008812/84e167a8-dc4c-11e6-8e5b-558021144339.png">

cc @jasich

**Comment by jasich** [comment]
Could you expand the description a bit? I'm guessing that is a Facebook comment in the screen shot.  Are you expecting it to show up with a 940x492 size image in the comments?

**Comment by jacebrowning** [comment]
Yeah. Do you think that is possible?

**Comment by jasich** [comment]
I'm not finding anything that might help, FYI you might want to read this [section](https://developers.facebook.com/docs/sharing/best-practices#images).  When talking about OpenGraph the docs only reference Posts not Comments.  I'm guessing what you show is controlled by them.

**Comment by jacebrowning** [comment]
I'll leave this issue open for a while in case someone knows the secrets of Facebook comments.

**Comment by jacebrowning** [comment]
🤷‍♂️
