### ISSUE TITLE
Using (alternative) fonts with masked URLs?

### ISSUE THREAD

**Issue by Aetheryx** [jacebrowning/memegen#337]
Is using alternative fonts with masked URLs possible?
https://memegen.link/wonka/testfield1/testfiel2.jpg?font=impact works, but https://memegen.link/_d29ua2EJZmllbGQtMS9maWVsZC0y.jpg?font=impact doesn't. Is there any other way of doing this I'm completely looking over? :(

**Comment by jacebrowning** [comment]
I don't think this is possible currently.

The [current implementation of masking](https://github.com/jacebrowning/memegen/blob/e56e790da9f207f84e1da18c9d28f0c4deceb02f/memegen/routes/image.py#L100-L106) only includes the template key and text path. This route should probably be updated to support at least the `font`, `share`, `width`, and `height` options.
