### ISSUE TITLE
Bad redirects from www

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#35]
Visiting  http://www.memegen.link/templates redirects back to http://memegen.link. I don't know to configure the NameCheap DNS to handle this...

**Comment by mattdiamond** [comment]
Hmm, I checked out the [Namecheap docs](https://www.namecheap.com/support/knowledgebase/article.aspx/385), and the relevant section is entitled **Redirect a domain/subdomain to a specific page on a website and pass values via query strings**. From what I'm reading, it seems like simply adding a trailing slash to the destination URL of the redirect (i.e. `http://memegen.link/`) may solve the problem.

**Comment by jacebrowning** [comment]
Like this?

<img width="807" alt="screen shot 2016-03-25 at 6 26 17 pm" src="https://cloud.githubusercontent.com/assets/939501/14055288/18fa3b48-f2b7-11e5-8db5-c3ed85ba50f7.png">

It will take some time for the change to be reflected...

**Comment by jacebrowning** [comment]
Hey, it's working. Thanks!
