### ISSUE TITLE
Watermark remove not working

### ISSUE THREAD

**Issue by anushkmittal** [jacebrowning/memegen#400]
https://memegen.link/buzz/memes/memes_everywhere.jpg?watermark=none should give an image without the watermark but it redirects to https://memegen.link/buzz/memes/memes_everywhere.jpg and the watermark is still displayed

**Comment by jacebrowning** [comment]
This is intentional. Only certain sites are allowed to disable the watermark (those set in `WATERMARK_OPTIONS`). I didn't document the `watermark=<str>` option because it's essentially for internal use.
