### ISSUE TITLE
Duplicate capitals not treated as a space.

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#43]
For example: http://memegen.link/success/ASpace.jpg

**Comment by nicolewhite** [comment]
Is this even a bug? Why wouldn't you just do http://memegen.link/success/A-Space.jpg

**Comment by jacebrowning** [comment]
The user could _could_ do that, but I've found that when typing words in Title Case, it's tempting to also type single letter words and acronyms following the same pattern: `IWantTHISPattern_to-Work` => ``i-want-this-patttern-to-work`. I'll reclassify this as an enhancement. Perhaps this will be too difficult to do...
