### ISSUE TITLE
Custom text layout should be possible for custom templates

### ISSUE THREAD

**Issue by mongolsamurai** [jacebrowning/memegen#434]
Custom templates should be able to specify text location and font size for each text field.

**Comment by jacebrowning** [comment]
I agree. If I built this project from scratch this would be possible. 

Do you have a proposal for how this could be added to the existing `config.yml`?

**Comment by mongolsamurai** [comment]
I'm working on one ^^
I'll open a PR if and when i get there

**Comment by jacebrowning** [comment]
I'm working on a rewrite of this API built on [Sanic](https://sanic.readthedocs.io). I have no idea when it will be done, but I'm planning to support arbitrary text layouts.

**Comment by jacebrowning** [comment]
This is possible with the v6.0 API:

![](https://api.memegen.link/images/ds/The_dress_is_black_and_blue./The_dress_is_gold_and_white..png)
