### ISSUE TITLE
Add instructions to create a Slack integration

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#46]

**Comment by CptSpaceToaster** [comment]
I'm taking a closer look at this.  I hope to hear back from the slack-team on a good way to respond with an attached image.  I can have a bot respond with the image as an attachment... but it looks a little funky still.  I'd like to have a user type a command, and then the integration would add the requested meme to the user's request as an attachment.  (Similar to `/giphy`)

More on this to come.

**Comment by nicolewhite** [comment]
I made one. I don't think the bot's response looks funky; it looks exactly like `/giphy`'s output. The only downside is that you can't use it in direct messages.

https://github.com/nicolewhite/slackbot-meme

**Comment by CptSpaceToaster** [comment]
@nicolewhite is the user's image just stored as `image_48` in the json response?
https://github.com/nicolewhite/slackbot-meme/blob/master/slack/models.py#L46  Or is that going to vary for every username?

**Comment by nicolewhite** [comment]
That's consistent across users. It's documented in Slack's API: https://api.slack.com/methods/users.info

**Comment by CptSpaceToaster** [comment]
Yeah... the bot still shows up as "BOT" next to the username, but other than that... I think this is the closest solution.  From my inquiry to the slack team.  Giphy uses undisclosed API's or a closed backend to add gifs as message attachments.

**Comment by nicolewhite** [comment]
Yeah I wasn't sure how giphy managed to post messages as the actual user. Like you said, I think this is the best we can do.

**Comment by CptSpaceToaster** [comment]
From them: 
```
Hi, CptSpaceToaster
The giphy slash command uses some magic (that we provided) to post the message as the user. You could do it by writing your command to each user's API token, but they'd each need to set up the integration individually.
My recommendation (and what I've done in the past for a couple of integrations on other teams) is change the name of the incoming webhook to something that fits with the spirit of the integration, then include the user's name in message that's sent through the webhook. The slash command payload that goes out will have the user's ID and username in it, so you can just echo those back into the webhook message.
Hope that helps!
Thanks,
David
```

**Comment by nicolewhite** [comment]
Yeah that's exactly what I'm doing. There's an Incoming Webhook where the channel, username, and icon are overridden for each request depending on which user made the request and from which channel.
