### ISSUE TITLE
Add text transformation to templates

### ISSUE THREAD

**Issue by kayladmae** [jacebrowning/memegen#478]
It would be nice to be able to define some kind of transformations to use in generation. For example, the Mocking Spongebob meme typically uses aLtErNaTiNg CaPs.

**Comment by jacebrowning** [comment]
This is available with v6.0 of the API.

https://github.com/jacebrowning/memegen/blob/main/templates/spongebob/config.yml produces: 

![](https://api.memegen.link/images/spongebob/BF:_I_don't_even_know_her_like_that/Me:_i_DoN'T_eVeN_KnOw_HeR_lIkE_tHaT.png)
