### ISSUE TITLE
Allow hyphens to be used through escaping

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#50]
From a comment on Hacker News:

> I don't seem to be able to use the hyphen (-) in text, it gets interpreted as a space (even when I URL-encode it as '%2D').

**Comment by nicolewhite** [comment]
What do you think this should look like? Can't escape with backslashes I suppose.

**Comment by CptSpaceToaster** [comment]
I don't think this is possible, but the user wanted %2D to be interpreted as a hyphen, and the `-` symbol to be a space.

**Comment by jacebrowning** [comment]
We could potentially follow the same pattern [shields.io](http://shields.io/#your-badge) uses:

> Dashes `--`	→	`-` Dash
> Underscores `__`	→	`_` Underscore 
> `_` or Space ` `	→	` ` Space

**Comment by CptSpaceToaster** [comment]
I think a single dash should also represent a space (Last line) but yeah... that sounds pretty good.

**Comment by jacebrowning** [comment]
Agreed. Keep the current behavior as well (Dash `-` → ` ` Space).

**Comment by nicolewhite** [comment]
:+1:
