### ISSUE TITLE
Fix Swagger validation errors

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#509]
https://validator.swagger.io/validator/debug?url=https://api.memegen.link/docs/swagger.json

**Comment by kyluca** [comment]
Hey Jace, I'd like to help out with this one, will let you know how I go in the next week or so.

An initial look makes it seem like it could be a sanic-openapi bug or something at that level. [The way](https://github.com/jacebrowning/memegen/blob/da63fa2de9f25e225736c49f8a4aec5be8d99b97/app/api/images.py#L25) you're doing `@doc.consumes` already looks correct but I can see why the resulting Swagger JSON is failing validation.

Cheers,
Kyle
