### ISSUE TITLE
Template validation should confirm `link` actually points to something

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#52]

**Comment by CptSpaceToaster** [comment]
I think you grabbed the wrong template
Try [this](http://cdn.meme.am/images/8689594.jpg) one
![so_happy](http://cdn.meme.am/images/8689594.jpg)
Example
![exe](http://cdn.meme.am/instances/250x250/54328812.jpg)

**Comment by jacebrowning** [comment]
@CptSpaceToaster Yeah, that's better! Want to send me a PR?
