### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by cpchen** [jacebrowning/memegen#525]
Do custom fonts still work? It looks like the section of the README that had custom fonts got taken away and 

https://api.memegen.link/images/joker/pick_a_different_font/people_lose_their_minds.jpg?font=typoline-demo

no longer changes the font.

**Comment by jacebrowning** [comment]
No there's only one default font since the rewrite with Sanic. I might add support for multiple fonts in the future, but it's not a priority right now.

The codebase with font support is here if you want to run your own instance: https://github.com/jacebrowning/memegen-flask

**Comment by jacebrowning** [comment]
@cpchen is there a particular font you'd like to see supported?

**Comment by cpchen** [comment]
Classic Impact!

**Comment by ryanaugustynowicz** [comment]
Can you support Noto Sans in the API?:
https://fonts.google.com/noto/specimen/Noto+Sans

It supports 855 languages and is open source.
It is under the Open Font License.

Thank you
