### ISSUE TITLE
Examples page gone?

### ISSUE THREAD

**Issue by karlhorky** [jacebrowning/memegen#546]
It looks like [the examples page](https://memegen.link/examples) no longer works - are there plans to bring that back?

It was a great way to see a lot of different memes and the format of the images all at once...

**Comment by jacebrowning** [comment]
It was lost in the rewrite, but I might bring it back at some point. Thanks for the feedback!

**Comment by karlhorky** [comment]
Cool, thanks!

**Comment by jacebrowning** [comment]
It's not equivalent, but https://api.memegen.link/samples is an undocumented route containing all the sample images.

**Comment by karlhorky** [comment]
Oh nice, yeah this may work! I guess the only difference is the design of the page? And that the page is undocumented?

**Comment by jacebrowning** [comment]
And that https://memegen.link is now a static site with the API deployed separately. Ultimately, I think I'll generate a static version of the API's samples page.

**Comment by jacebrowning** [comment]
https://memegen.link/examples is back in a new form. I'll probably keep iterating on this.

**Comment by karlhorky** [comment]
Great, thanks for that!
