### ISSUE TITLE
Install the API for PHP web app 

### ISSUE THREAD

**Issue by minaeshak** [jacebrowning/memegen#560]
Hello ,

Could you assist me how to install your API on my php web application ?

Thanks ,
Mina

**Comment by jacebrowning** [comment]
https://api.memegen.link/docs/ will show you what the API calls look using `curl`, which you'll need to translate to HTTP requests in PHP, using something like [Guzzle](https://docs.guzzlephp.org/).

You could also look into generating PHP client code using [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) and the Swagger spec for this API: https://api.memegen.link/docs/swagger.json
