### ISSUE TITLE
Option to remove watermark

### ISSUE THREAD

**Issue by BreadBreadington** [jacebrowning/memegen#562]
Any chance you'd add a way to remove the watermark from generated images? 

Been using this API for a while to generate memes in Discord with a few friends since we were sick of NotSoBot always being down.
I've changed the bot recently to upload the image generated rather than posting the URL since I find that a little more elegant.

Previously there was a pretty simple way to remove the watermark when posting the URL but since I'd prefer uploading the raw image, I no longer have that option (Or my knowledge of HTTP requests is too limited to create another workaround)

**Comment by jacebrowning** [comment]
Not at this time since watermarks are the primary way people discover this service. 😄 

In the future I might considered a crowdfunded model where authenticated requests can generate plain images.

**Comment by jacebrowning** [comment]
Authenticated API requests are now watermark-free: https://github.com/jacebrowning/memegen#authentication
