### ISSUE TITLE
Support custom images as templates

### ISSUE THREAD

**Issue by nicolewhite** [jacebrowning/memegen#58]
Any plans to allow for custom images, similar to what memeifier allows? So like this:

http://memegen.link/http://nicolewhite.github.io/static/me.jpg/hello/world.jpg

The memeifier link:

http://memeifier.com/hello/world/http://nicolewhite.github.io/static/me.jpg

**Comment by jacebrowning** [comment]
Hmmm... you're the second person to ask for this, so I guess I should consider it! :smile: 

If it's a common meme I'd rather someone add it to the templates, but I could see other cases where a "private" image might be used. Currently, MemeGen handles an unlimited number of lines of text for future support of memes with more than two lines of text. This means that it will be hard to disambiguate

`/<key>/line1/line2_with_periods/line3`

from

`/<url>/line3`

What about `/custom/line_1/line_2/line_n.jpg?url=http://example.com/image.png`?

**Comment by nicolewhite** [comment]
I like the second option!

**Comment by jacebrowning** [comment]
@nicolewhite https://github.com/jacebrowning/memegen/pull/189 will add support for this:

https://memegen-link-pr-189.herokuapp.com/custom/my-pretty/background.jpg?alt=http://www.gstatic.com/webp/gallery/1.jpg

which produces:

![](https://memegen-link-pr-189.herokuapp.com/custom/my-pretty/background.jpg?alt=http://www.gstatic.com/webp/gallery/1.jpg)

Thoughts?

**Comment by jacebrowning** [comment]
`/custom` is not actually special here. `?alt=http://...` can be tacked on to any image URL.

**Comment by nicolewhite** [comment]
Yay that's awesome! So you're saying I could also do something like:

`/success/top/bottom/?alt=http://...` and it would replace the success meme with the image I provide?

**Comment by jacebrowning** [comment]
Yes.

**Comment by nicolewhite** [comment]
Sweet. I'll make the changes when it's pushed.

**Comment by jacebrowning** [comment]
But please note that doing so can also trigger this bug if the exact same text is required using two different images: https://github.com/jacebrowning/memegen/issues/188

I'm going to merge this change and work on fixing that bug.

**Comment by jacebrowning** [comment]
It's live now: http://memegen.link/custom/my-pretty/background.jpg?alt=http://www.gstatic.com/webp/gallery/1.jpg
