### ISSUE TITLE
Add an easier way to type question marks

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#63]
Because a `?` character starts the query parameters, it can't be typed directly into the URL bar. It would be nice if there was a short code to type `?`, such as:

* `{question}`
* `[q]`
* `^q`
* etc.

**Comment by jacebrowning** [comment]
Or, add a setting that causes certain memes to always end in a question mark.

**Comment by CptSpaceToaster** [comment]
![not-sure]http://memgen.link/afraid/do-you-think-that-will-work%3F-What-about/Question-marks-in-the-middle-of-the-text%3F

**Comment by nicolewhite** [comment]
I don't think forced question marks are a good idea.

**Comment by CptSpaceToaster** [comment]
in my opinion `[q]` sounds like a best idea so far

I'd love if `??` could be hooked somehow... or `\?` or something escaping the question mark... but that sounds like it'd require a significant amount of work on the backend.

**Comment by jacebrowning** [comment]
If brackets are used to escape symbols (`[<symbol shortcut>]`, does there need to be a way to escape brackets? (e.g. `[[text actually inside brackets]]`) Or, are brackets seldom used in memes?

**Comment by nicolewhite** [comment]
Can you not grab whatever was intended to be the meme's text out of `request.args`?

**Comment by jacebrowning** [comment]
@nicolewhite For what purpose?

Now that I think about it, it's very unlikely someone will need a literal `[q]` in their meme text.

**Comment by nicolewhite** [comment]
Well, it seems like the problem is that you can't type a literal `?` into the URL because it will truncate the rest. So `http://memegen.link/success/hello?/hello?` ends up being `http://memegen.link/success/hello`. If you checked what was in `request.args`, you'd get everything that was included past the `?` no?

**Comment by jacebrowning** [comment]
I'll take a look. Are you proposing to do that in lieu of escaping?

**Comment by nicolewhite** [comment]
I'm actually thinking it won't work as `request.args` only lets you grab named parameters (I think?), and whatever ends up in there would surely be malformed.

I think it'd be fine to let `[q]` be a reserved sequence that maps to a question mark.

**Comment by jacebrowning** [comment]
:+1:

**Comment by jacebrowning** [comment]
I'm going to use tildes rather than brackets, because they're URL-safe.
