### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#64]

**Comment by joshfriend** [comment]
![gnome](https://cloud.githubusercontent.com/assets/885137/9139159/5f490f1a-3cf6-11e5-8850-f748fc080dde.png)

**Comment by jacebrowning** [comment]
I added a really terrible placeholder: http://memegen.link/

**Comment by CptSpaceToaster** [comment]
?

![Is This It?](http://i.imgur.com/3zKUWXk.png)

**Comment by joshfriend** [comment]
![ahem](http://i.imgur.com/DQwbWpr.png)

**Comment by CptSpaceToaster** [comment]
![Well now](http://i.imgur.com/yHpOFwX.png)

![I'll just leave this here](http://i.imgur.com/MWg8sz0.gif)

**Comment by jacebrowning** [comment]
Done!

![memegen](https://cloud.githubusercontent.com/assets/939501/10960240/a13997e6-8350-11e5-89bb-59e866c074ab.png)
