### ISSUE TITLE
Hide links column in Swagger UI

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#680]
![](https://cdn.zappy.app/abac6945b345f7b13967dfa5b2116f48.png)

**Comment by Vethya** [comment]
Hey! I'm new here and I want to make some contributions. The documentation doesn't seem to be related to the code, can you tell me how I will resolve this issue?

**Comment by jacebrowning** [comment]
Since the Swagger UI is simply powered by the OpenAPI specification, I doubt anything can be done here.
