### ISSUE TITLE
CORS issue with custom endpoint

### ISSUE THREAD

**Issue by Josehower** [jacebrowning/memegen#695]
Hi, similarly to the issue that templates had last week.

I found custom endpoint seems to have a CORS problem

[The app ](https://confident-murdock-f29b36.netlify.app/) of one of our students  seems to fail when trying to use the custom endpoint

<img width="704" alt="image" src="https://user-images.githubusercontent.com/61600906/154963013-a24db4cb-d1e8-4f88-a9d9-a3744de3a8cb.png">

I am unsure if this may be also a cache problem but seems to me that this may be a different bug related to  https://github.com/jacebrowning/memegen/issues/687

Thanks in advance for your attention to this issue.

**Comment by jacebrowning** [comment]
Can you show me what Response Headers you're getting?

**Comment by Josehower** [comment]
Thanks! 🎉
