### ISSUE TITLE
Memegen fails to service an image if %2F is used in the macro-text

### ISSUE THREAD

**Issue by CptSpaceToaster** [jacebrowning/memegen#71]
Example Link: http://memegen.link/buzz/%2Fcollapse/%2Fcollapse-everywhere.jpg

%2F is the ever popular forward slash `/` and I think it's being encoded in an odd way.  I'm not sure if this is an actual bug... Does anyone know if this issue is of concern?

**Comment by joshfriend** [comment]
Don't think anything can be done about this:

mitsuhiko/flask#900
mitsuhiko/werkzeug#477

**Comment by CptSpaceToaster** [comment]
Makes sense
