### ISSUE TITLE
Cannot include a forward slash in macro text

### ISSUE THREAD

**Issue by CptSpaceToaster** [jacebrowning/memegen#72]
Both `/` and %2F can not be used in a URL, as both characters will be treated as relevant characters to the path.  Can we come up with a sufficient alternative or escape sequence that will output `/` in an image's macro text?

**Comment by CptSpaceToaster** [comment]
Related: https://github.com/jacebrowning/memegen/issues/63

**Comment by jacebrowning** [comment]
`~s` could map to `/` in the text.

**Comment by nicolewhite** [comment]
Somewhat related: do you have a glossary of these reserved mappings somewhere?

**Comment by jacebrowning** [comment]
@nicolewhite They're in the README: https://github.com/jacebrowning/memegen#special-characters

And currently in the `Text` domain model (with a serious need for refactoring):

- https://github.com/jacebrowning/memegen/blob/ccc502c2cbae44e8e7eb2d21b5985fb60e998e1f/memegen/domain/text.py#L57-60
- https://github.com/jacebrowning/memegen/blob/ccc502c2cbae44e8e7eb2d21b5985fb60e998e1f/memegen/domain/text.py#L103-104

**Comment by joshfriend** [comment]
What if you allow people to use querystring arguments instead?

`http://memegen.link/iw?t=Top_text&b=Bottom_text`

**Comment by jacebrowning** [comment]
@joshfriend And then use `%2F` in the querystring? That could work, but I probably wouldn't want to type that out by hand.

**Comment by joshfriend** [comment]
if the slash is in the querystring, it doesn't need encoding at all
