### ISSUE TITLE
Suggestion on using QR codes to link to images

### ISSUE THREAD

**Issue by dargrall** [jacebrowning/memegen#721]
Not an Issue but I thought I would drop it here. You can easily generate QR-Codes that lead to those links and print them on stickers or Paper for T-Shirts, Skateboards or whatever. At least thats what I'm going to do.

**Comment by jacebrowning** [comment]
> that lead to those links

What links?

**Comment by dargrall** [comment]
Well if you generate a QR-Code from the URL you can use those QR-Codes to troll or amuse people:
![qr-code](https://user-images.githubusercontent.com/46103191/175521367-404f50b9-53b7-4f35-901c-1cd2208dcb2f.png)
