### ISSUE TITLE
WebP is probably being generated with the wrong mime

### ISSUE THREAD

**Issue by Helvio88** [jacebrowning/memegen#768]
Please try to open:
https://api.memegen.link/images/buzz/memes/memes_everywhere.webp
You'd get the binary data.

It worked on the Heroku app and also works on Docker. Must be a webserver/proxy issue.

---

Uncomment these lines when the bug is fixed:

https://github.com/jacebrowning/memegen/blob/9307cc4f49903349f3f334e33e19c88f709f1768/app/tests/test_views_images.py#L151-L155

**Comment by jacebrowning** [comment]
Yeah, the browser console says this is being returned as `text/plain`. The image _does_ display correctly in Slack. 🤔

**Comment by Helvio88** [comment]
I see that the second loop wasn't necessary. Go figure. I could have swore I tried that before! Thanks for pointing that out!

**Comment by jacebrowning** [comment]
Yeah, potentially the extension could be passed in to update [this line](https://github.com/jacebrowning/memegen/blob/e93afb89354ec7dd3ad3cfa6fad761febd5667d0/app/utils/images.py#L351) but I don't think wrapping the `frames` in `Image` was doing anything.

**Comment by jacebrowning** [comment]
This seems to be the root cause: https://bugs.python.org/issue38902

I'll try hard-coding `image/webp` for now.

**Comment by Helvio88** [comment]
That's crazy. Funny how it worked on Docker. I hope they fix that soon.

**Comment by jacebrowning** [comment]
It sounds like the database of file types might vary slightly between distributions of Python, so I guess Heroku's Python is missing the `webp` support.
