### ISSUE TITLE
Cannot add space before dash

### ISSUE THREAD

**Issue by LatinSuD** [jacebrowning/memegen#828]
I want the caption to be this:

`kill -9`

This has special characters, so the URL has to be crafted carefully. First a "_" for the space, then "-- " for the dash.

So I use this URL:
https://api.memegen.link/images/custom/kill_--9.jpg?font=impact&background=https://www.latinsud.com/pub/meme/files/the-matrix-morfeo-morpheus-what-if-i-told-you.jpg

As soon as I type it it gets replaced by this one:
https://api.memegen.link/images/custom/kill--_9.jpg?font=impact&background=https://www.latinsud.com/pub/meme/files/the-matrix-morfeo-morpheus-what-if-i-told-you.jpg

And the result is missing a space.

**Comment by LatinSuD** [comment]
I found a workaround, using non-breaking space (%C2%A0), but it's just a workaround.

https://api.memegen.link/images/custom/kill%C2%A0--9.jpg?font=impact&background=https://www.latinsud.com/pub/meme/files/the-matrix-morfeo-morpheus-what-if-i-told-you.jpg

**Comment by jacebrowning** [comment]
Thanks for the report! #829 should fix this.
