### ISSUE TITLE
Potential race condition with custom template parameters breaking defaults

### ISSUE THREAD

**Issue by kishan-character** [jacebrowning/memegen#857]
I think the API might have recently broken...

I made this yesterday:
https://api.memegen.link/images/pigeon/Programmer_looking_at_code/Code_with_no_errors/Is_this_magic~q.png

if i try creating a new one now, it doesn't show the third caption:
https://api.memegen.link/images/pigeon/1/2/3~q.png

**Comment by jacebrowning** [comment]
@kishan-character both of those links seem to be working now. I do think there is a race condition bug with custom template parameters conflicting with the existing YAML definition on the server so I'll keep this option.
