### ISSUE TITLE
Add a Font that Supports the Japanese Language

### ISSUE THREAD

**Issue by robert-huang** [jacebrowning/memegen#866]
Currently the available fonts don't support displaying kanji or kana in the text of the images. 
e.g. https://api.memegen.link/images/pigeon/Engineer/_/Is_this_%E9%AB%98%E6%9C%A8%E3%81%95%E3%82%93~q.png?font=segoe&style=https://m.media-amazon.com/images/I/71XOupccufL.jpg

It looks like HG Mincho B is under the CC0 license. 
https://japanesefonts.org/hg-mincho-b.html

If that sounds ok, I can make a PR to add that as a supported language.

**Comment by jacebrowning** [comment]
Were any of the exiting fonts _expected_ to support Japanese? I'm not opposed to adding another font if it doesn't increase the build size too much.

**Comment by robert-huang** [comment]
I tested out the existing fonts and I don't believe any of them have that part of the character set.

The font is 3.5 MB, so a bit larger than the current fonts, but pretty small overall, is that acceptable?

**Comment by jacebrowning** [comment]
Yeah, that's fine.

**Comment by robert-huang** [comment]
#868 868
