### ISSUE TITLE
Feature Request: Emoji support?

### ISSUE THREAD

**Issue by Vivinn-c** [jacebrowning/memegen#878]
Hey! I've been using memegen for a while now, and I've always wanted a feature to be added. Is it possible to support emojis when creating memes? Thanks!

**Comment by jacebrowning** [comment]
It comes down to which unicode characters are supported by a particular font.

For example, `☺` works with Impact: https://api.memegen.link/images/fry/unicode_test:_☺.webp?font=impact

![](https://api.memegen.link/images/fry/unicode_test:_☺.webp?font=impact)

You'd likely have to do some testing to see which of the [available fonts](https://api.memegen.link/fonts) have what you need.

**Comment by Vivinn-c** [comment]
Hmm, looks like [noto sans color emojis](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) might be good for handling emojis

**Comment by jacebrowning** [comment]
I tried adding that font in https://github.com/jacebrowning/memegen/pull/880 but it doesn't seem to be working: https://memegen-pr-880.herokuapp.com/images/fry/test_%F0%9F%98%AC.png?font=emoji

Any ideas?

**Comment by Vivinn-c** [comment]
Hmm, looks like Pillow doesn't support noto emoji, hmm
https://github.com/python-pillow/Pillow/issues/3346#issuecomment-612139601

**Comment by Vivinn-c** [comment]
Looks like using [Segoe UI Emoji](https://fontsdata.com/132714/segoeuiemoji.htm) works best

embedded_color=False
![image](https://github.com/user-attachments/assets/33536a9a-97c3-40b9-86ed-c9c0b2057e87)
embedded_color=True
![image](https://github.com/user-attachments/assets/e3594c57-f47e-465a-a4f6-3c37052a63a0)

**Comment by Vivinn-c** [comment]
The cons of adding segiumj.ttf is that it may cause the outline to shift slightly out of alignment, if embedded_color is set to True.

**Comment by Vivinn-c** [comment]
Looks like memgen can process emojis without eexternal font support by using Pilmoji
