### ISSUE TITLE
Improve auto refresh on "latest meme" page

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/memegen#94]
Someone who is better at HTML/JavaScript could make this reload just the image and/or only reload when the images changes.

**Comment by craiglabenz** [comment]
You want to catch CMD-Rs from the user?

**Comment by jacebrowning** [comment]
I was referring to making the **automatic** refreshes better: https://github.com/jacebrowning/memegen/blob/d187423d844b5a8a9911840af80c110dd6fa2c7c/memegen/templates/latest.html#L5

I believe that some JavaScript could automatically reload **just** the image when it changes.
